---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  - excalidraw.yaml
  - excalidraw-2.yaml

configMapGenerator:
  - name: excalidraw
    files:
      - files/Dockerfile

generatorOptions:
  disableNameSuffixHash: true
