---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configMap.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/namespace.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/metallb.yaml
