---
## Nexus
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "resume-dot-danmanners-dot-com"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:danmanners/homelab-k3s-cluster.git"
    path: manifests/workloads/resume-dot-danmanners-dot-com
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: resume-dot-danmanners-dot-com
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
