---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-prod
spec:
  acme:
    email: daniel.a.manners@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-prod-account-key
    solvers:
    - dns01:
        route53:
          region: us-east-1
          accessKeyID: AKIA6HIHA6ONQID7DMEI
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key
      selector:
        dnsZones:
        - 'danmanners.com'
        - 'danmanners.io'
        - 'k3s.danmanners.io'
