---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ots

helmCharts:
  - name: redis-cluster
    releaseName: redis
    namespace: ots
    repo: https://charts.bitnami.com/bitnami
    version: "7.6.0"
    valuesFile: values.yaml

patchesStrategicMerge: 
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: redis-redis-cluster
    $patch: delete
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: redis-redis-cluster-default
    $patch: delete