---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: nvidia-device-plugin
    releaseName: nvidia-device-plugin
    repo: https://nvidia.github.io/k8s-device-plugin
    version: "0.11.0"
    valuesInline:
      runtimeClassName: nvidia

resources:
  - gpu-extension.yaml
  - test-pod.yaml
