apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-pr
spec:
  # serviceAccountName: tekton-triggers-example-sa
  triggers:
  - name: github-listener
    interceptors:
    - ref:
        name: "github"
      params:
      - name: secret
        value:
          secretName: github-interceptor-secret
          secretKey: secretToken
      - name: "eventTypes"
        value: ["pull_request"]
    - ref:
        name: "cel"
      params:
      - name: "filter"
        value: "body.action in ['opened', 'synchronize', 'reopened']"
    bindings:
    - ref: github-pr-binding
    template:
      ref: github-pr-pipeline-template
