---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.1/manifests/install.yaml
  - ingress.yaml
  - services.yaml
patchesStrategicMerge:
  - deployment.yaml
  - configmap.yaml