---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nda
  name: nda
  namespace: nda
  annotations:
    fluxcd.io/automated: "true"
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  selector:
    matchLabels:
      run: nda
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nda
    spec:
      containers:
      - image: danielmanners/non-disclosure-agreement:latest
        imagePullPolicy: Always
        name: website
        resources:
          limits:
            cpu: "1"
            memory: 160Mi
          requests:
            cpu: 500m
            memory: 96Mi
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 3