---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: kube-prometheus-stack
    releaseName: monitoring
    namespace: kube-system
    repo: https://prometheus-community.github.io/helm-charts
    version: "35.5.1"
    valuesFile: values.yaml

resources:
  # Files
  - ingress.yaml
  - service.yaml
