---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor

resources:
  - ns.yaml
  - ingress.yaml

helmCharts:
  - releaseName: harbor
    name: harbor
    namespace: harbor
    repo: https://helm.goharbor.io
    version: "1.9.2"
    valuesFile: values.yaml
