---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: copy-file
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Developer Tools
    tekton.dev/tags: generic
    tekton.dev/displayName: Copy a file from one workspace to another
    tekton.dev/platforms: "linux/amd64,linux/arm64,linux/s390x,linux/ppc64le"
spec:
  params:
    - name: source-files
      type: string
    - name: dest-files
      type: string
  workspaces:
    - name: source
      description: Source Workspace
    - name: dest
      description: Destination Workspace
  steps:
    - name: copy-file
      image: docker.io/library/alpine:3.16
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -eu
        echo "Source Files:"
        ls -halt $(workspaces.source.path)
        echo "========================"
        echo "Destination Files:"
        ls -halt $(workspaces.dest.path)
        echo "========================"
        echo "Copying $(workspaces.source.path)/$(params.source-files) to $(workspaces.dest.path)/$(params.dest-files)"
        cp -Lr $(workspaces.source.path)/$(params.source-files) $(workspaces.dest.path)/$(params.dest-files)
        echo "========================"
        echo "Post-Copy Destination:"
        ls -halt $(workspaces.dest.path)
