---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph

helmCharts:
  - name: rook-ceph-cluster
    releaseName: rook-ceph-cluster
    namespace: rook-ceph
    repo: https://charts.rook.io/release
    version: v1.12.3
    valuesFile: values.yaml
